import { Source_Sans_3 } from 'next/font/google';
import './globals.scss';
import { ReduxProvider } from '../store/providers';

interface Metadata {
  title: string;
  description: string;
}

interface Viewport {
  width: string;
  initialScale: number;
  maximumScale: number;
  userScalable: boolean;
}

const sourceSansPro = Source_Sans_3({
  subsets: ['latin', 'cyrillic'],
  weight: ['200', '300', '400', '600', '700', '900'],
  style: ['normal', 'italic'],
  variable: '--font-source-sans-pro',
  display: 'swap',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

interface LayoutProps {
  children: React.ReactNode;
}

export default function Layout({ children }: LayoutProps) {
  return (
    <html lang='en'>
      <body className={sourceSansPro.variable}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
